apiVersion: v1
kind: Secret
metadata:
  name: crm-secrets
  namespace: crm-supermercado
type: Opaque
stringData:
  postgres-password: "supersecret-postgres-password"
  rabbitmq-password: "supersecret-rabbitmq-password"
  jwt-secret: "your-jwt-secret-with-at-least-32-characters"
  aes-256-key: "your-aes-256-key-that-is-exactly-32-bytes"
  database-url: "postgresql://admin:supersecret-postgres-password@postgres:5432/crm_supermercado"
  grafana-password: "admin"
---
apiVersion: v1
kind: Secret
metadata:
  name: crm-secrets
  namespace: crm-monitoring
type: Opaque
stringData:
  grafana-password: "admin"
