name: offline
description: Shared offline support and sync queue for Flutter mobile apps
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.0
  path: ^1.8.3
  connectivity_plus: ^5.0.2
  http: ^1.1.0
  path_provider: ^2.1.1
