import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const cidadesPorUf: Record<string, { codigo: string; nome: string; regiao: string }[]> = {
  AC: [
    { codigo: '1200013', nome: 'Rio Branco', regiao: 'Norte' },
    { codigo: '1200054', nome: 'Cruzeiro do Sul', regiao: 'Norte' },
    { codigo: '1200203', nome: 'Sena Madureira', regiao: 'Norte' },
    { codigo: '1200138', nome: 'Tarauacá', regiao: 'Norte' },
    { codigo: '1200179', nome: 'Feijó', regiao: 'Norte' },
    { codigo: '1200252', nome: 'Brasiléia', regiao: 'Norte' },
    { codigo: '1200302', nome: 'Xapuri', regiao: 'Norte' },
    { codigo: '1200104', nome: 'Plácido de Castro', regiao: 'Norte' },
    { codigo: '1200385', nome: 'Senador Guiomard', regiao: 'Norte' },
    { codigo: '1200807', nome: 'Mâncio Lima', regiao: 'Norte' },
  ],
  AL: [
    { codigo: '2704302', nome: 'Maceió', regiao: 'Nordeste' },
    { codigo: '2701006', nome: 'Arapiraca', regiao: 'Nordeste' },
    { codigo: '2700301', nome: 'Rio Largo', regiao: 'Nordeste' },
    { codigo: '2708901', nome: 'Palmeira dos Índios', regiao: 'Nordeste' },
    { codigo: '2707705', nome: 'União dos Palmares', regiao: 'Nordeste' },
    { codigo: '2703205', nome: 'Coruripe', regiao: 'Nordeste' },
    { codigo: '2706400', nome: 'São Miguel dos Campos', regiao: 'Nordeste' },
    { codigo: '2704708', nome: 'Marechal Deodoro', regiao: 'Nordeste' },
    { codigo: '2706301', nome: 'Santana do Ipanema', regiao: 'Nordeste' },
    { codigo: '2709156', nome: 'Delmiro Gouveia', regiao: 'Nordeste' },
    { codigo: '2702504', nome: 'Penedo', regiao: 'Nordeste' },
    { codigo: '2701402', nome: 'Campo Alegre', regiao: 'Nordeste' },
  ],
  AP: [
    { codigo: '1600303', nome: 'Macapá', regiao: 'Norte' },
    { codigo: '1600600', nome: 'Santana', regiao: 'Norte' },
    { codigo: '1600401', nome: 'Laranjal do Jari', regiao: 'Norte' },
    { codigo: '1600500', nome: 'Oiapoque', regiao: 'Norte' },
    { codigo: '1600105', nome: 'Amapá', regiao: 'Norte' },
    { codigo: '1600204', nome: 'Calçoene', regiao: 'Norte' },
    { codigo: '1600559', nome: 'Porto Grande', regiao: 'Norte' },
    { codigo: '1600808', nome: 'Tartarugalzinho', regiao: 'Norte' },
    { codigo: '1600709', nome: 'Serra do Navio', regiao: 'Norte' },
    { codigo: '1600154', nome: 'Pedra Branca do Amapari', regiao: 'Norte' },
  ],
  AM: [
    { codigo: '1302603', nome: 'Manaus', regiao: 'Norte' },
    { codigo: '1303403', nome: 'Parintins', regiao: 'Norte' },
    { codigo: '1301902', nome: 'Itacoatiara', regiao: 'Norte' },
    { codigo: '1301209', nome: 'Coari', regiao: 'Norte' },
    { codigo: '1301803', nome: 'Humaitá', regiao: 'Norte' },
    { codigo: '1304203', nome: 'Tabatinga', regiao: 'Norte' },
    { codigo: '1301100', nome: 'Careiro', regiao: 'Norte' },
    { codigo: '1302504', nome: 'Manacapuru', regiao: 'Norte' },
    { codigo: '1302405', nome: 'Maués', regiao: 'Norte' },
    { codigo: '1301308', nome: 'Eirunepé', regiao: 'Norte' },
    { codigo: '1301605', nome: 'Fonte Boa', regiao: 'Norte' },
    { codigo: '1303536', nome: 'Presidente Figueiredo', regiao: 'Norte' },
  ],
  BA: [
    { codigo: '2927408', nome: 'Salvador', regiao: 'Nordeste' },
    { codigo: '2910800', nome: 'Feira de Santana', regiao: 'Nordeste' },
    { codigo: '2928703', nome: 'Vitória da Conquista', regiao: 'Nordeste' },
    { codigo: '2933307', nome: 'Camaçari', regiao: 'Nordeste' },
    { codigo: '2905701', nome: 'Barreiras', regiao: 'Nordeste' },
    { codigo: '2914808', nome: 'Ilhéus', regiao: 'Nordeste' },
    { codigo: '2913602', nome: 'Guanambi', regiao: 'Nordeste' },
    { codigo: '2925303', nome: 'Porto Seguro', regiao: 'Nordeste' },
    { codigo: '2929206', nome: 'Alagoinhas', regiao: 'Nordeste' },
    { codigo: '2914402', nome: 'Jequié', regiao: 'Nordeste' },
    { codigo: '2902307', nome: 'Eunápolis', regiao: 'Nordeste' },
    { codigo: '2931354', nome: 'Lauro de Freitas', regiao: 'Nordeste' },
    { codigo: '2921101', nome: 'Luis Eduardo Magalhães', regiao: 'Nordeste' },
    { codigo: '2930709', nome: 'Santo Antônio de Jesus', regiao: 'Nordeste' },
  ],
  CE: [
    { codigo: '2304400', nome: 'Fortaleza', regiao: 'Nordeste' },
    { codigo: '2303700', nome: 'Caucaia', regiao: 'Nordeste' },
    { codigo: '2307700', nome: 'Juazeiro do Norte', regiao: 'Nordeste' },
    { codigo: '2304202', nome: 'Maracanaú', regiao: 'Nordeste' },
    { codigo: '2306101', nome: 'Sobral', regiao: 'Nordeste' },
    { codigo: '2301100', nome: 'Crato', regiao: 'Nordeste' },
    { codigo: '2307650', nome: 'Iguatu', regiao: 'Nordeste' },
    { codigo: '2308302', nome: 'Quixadá', regiao: 'Nordeste' },
    { codigo: '2309607', nome: 'Pacatuba', regiao: 'Nordeste' },
    { codigo: '2305235', nome: 'Aquiraz', regiao: 'Nordeste' },
    { codigo: '2300201', nome: 'Aracati', regiao: 'Nordeste' },
    { codigo: '2306309', nome: 'Canindé', regiao: 'Nordeste' },
  ],
  DF: [
    { codigo: '5300108', nome: 'Brasília', regiao: 'Centro-Oeste' },
    { codigo: '5300109', nome: 'Ceilândia', regiao: 'Centro-Oeste' },
    { codigo: '5300110', nome: 'Taguatinga', regiao: 'Centro-Oeste' },
    { codigo: '5300111', nome: 'Plano Piloto', regiao: 'Centro-Oeste' },
    { codigo: '5300112', nome: 'Samambaia', regiao: 'Centro-Oeste' },
    { codigo: '5300113', nome: 'Águas Claras', regiao: 'Centro-Oeste' },
    { codigo: '5300114', nome: 'Recanto das Emas', regiao: 'Centro-Oeste' },
    { codigo: '5300115', nome: 'Gama', regiao: 'Centro-Oeste' },
    { codigo: '5300116', nome: 'Santa Maria', regiao: 'Centro-Oeste' },
    { codigo: '5300117', nome: 'Guará', regiao: 'Centro-Oeste' },
    { codigo: '5300118', nome: 'Sobradinho', regiao: 'Centro-Oeste' },
    { codigo: '5300119', nome: 'Planaltina', regiao: 'Centro-Oeste' },
  ],
  ES: [
    { codigo: '3205309', nome: 'Vitória', regiao: 'Sudeste' },
    { codigo: '3205200', nome: 'Vila Velha', regiao: 'Sudeste' },
    { codigo: '3205101', nome: 'Serra', regiao: 'Sudeste' },
    { codigo: '3201308', nome: 'Cariacica', regiao: 'Sudeste' },
    { codigo: '3202405', nome: 'Linhares', regiao: 'Sudeste' },
    { codigo: '3204906', nome: 'São Mateus', regiao: 'Sudeste' },
    { codigo: '3201407', nome: 'Colatina', regiao: 'Sudeste' },
    { codigo: '3203908', nome: 'Guarapari', regiao: 'Sudeste' },
    { codigo: '3202207', nome: 'Aracruz', regiao: 'Sudeste' },
    { codigo: '3201209', nome: 'Cachoeiro de Itapemirim', regiao: 'Sudeste' },
    { codigo: '3201506', nome: 'Nova Venécia', regiao: 'Sudeste' },
    { codigo: '3201704', nome: 'Venda Nova do Imigrante', regiao: 'Sudeste' },
  ],
  GO: [
    { codigo: '5208707', nome: 'Goiânia', regiao: 'Centro-Oeste' },
    { codigo: '5201108', nome: 'Anápolis', regiao: 'Centro-Oeste' },
    { codigo: '5211501', nome: 'Rio Verde', regiao: 'Centro-Oeste' },
    { codigo: '5201405', nome: 'Aparecida de Goiânia', regiao: 'Centro-Oeste' },
    { codigo: '5208004', nome: 'Jataí', regiao: 'Centro-Oeste' },
    { codigo: '5211907', nome: 'Luziânia', regiao: 'Centro-Oeste' },
    { codigo: '5218000', nome: 'Catalão', regiao: 'Centro-Oeste' },
    { codigo: '5220458', nome: 'Itumbiara', regiao: 'Centro-Oeste' },
    { codigo: '5209705', nome: 'Caldas Novas', regiao: 'Centro-Oeste' },
    { codigo: '5205109', nome: 'Formosa', regiao: 'Centro-Oeste' },
    { codigo: '5200300', nome: 'Águas Lindas de Goiás', regiao: 'Centro-Oeste' },
    { codigo: '5205497', nome: 'Valparaíso de Goiás', regiao: 'Centro-Oeste' },
  ],
  MA: [
    { codigo: '2111300', nome: 'São Luís', regiao: 'Nordeste' },
    { codigo: '2107500', nome: 'Imperatriz', regiao: 'Nordeste' },
    { codigo: '2105302', nome: 'Timon', regiao: 'Nordeste' },
    { codigo: '2101400', nome: 'Caxias', regiao: 'Nordeste' },
    { codigo: '2103300', nome: 'Codó', regiao: 'Nordeste' },
    { codigo: '2100050', nome: 'Açailândia', regiao: 'Nordeste' },
    { codigo: '2102200', nome: 'Bacabal', regiao: 'Nordeste' },
    { codigo: '2103607', nome: 'Santa Inês', regiao: 'Nordeste' },
    { codigo: '2101202', nome: 'Chapadinha', regiao: 'Nordeste' },
    { codigo: '2101707', nome: 'Pinheiro', regiao: 'Nordeste' },
    { codigo: '2108201', nome: 'Paço do Lumiar', regiao: 'Nordeste' },
    { codigo: '2109050', nome: 'São José de Ribamar', regiao: 'Nordeste' },
  ],
  MT: [
    { codigo: '5103403', nome: 'Cuiabá', regiao: 'Centro-Oeste' },
    { codigo: '5108402', nome: 'Várzea Grande', regiao: 'Centro-Oeste' },
    { codigo: '5107603', nome: 'Rondonópolis', regiao: 'Centro-Oeste' },
    { codigo: '5100250', nome: 'Sinop', regiao: 'Centro-Oeste' },
    { codigo: '5103205', nome: 'Tangará da Serra', regiao: 'Centro-Oeste' },
    { codigo: '5101704', nome: 'Cáceres', regiao: 'Centro-Oeste' },
    { codigo: '5102504', nome: 'Lucas do Rio Verde', regiao: 'Centro-Oeste' },
    { codigo: '5107900', nome: 'Sorriso', regiao: 'Centro-Oeste' },
    { codigo: '5101803', nome: 'Barra do Garças', regiao: 'Centro-Oeste' },
    { codigo: '5105104', nome: 'Primavera do Leste', regiao: 'Centro-Oeste' },
    { codigo: '5106225', nome: 'Nova Mutum', regiao: 'Centro-Oeste' },
    { codigo: '5103502', nome: 'Colíder', regiao: 'Centro-Oeste' },
  ],
  MS: [
    { codigo: '5002704', nome: 'Campo Grande', regiao: 'Centro-Oeste' },
    { codigo: '5003207', nome: 'Dourados', regiao: 'Centro-Oeste' },
    { codigo: '5008305', nome: 'Três Lagoas', regiao: 'Centro-Oeste' },
    { codigo: '5001100', nome: 'Corumbá', regiao: 'Centro-Oeste' },
    { codigo: '5003702', nome: 'Ponta Porã', regiao: 'Centro-Oeste' },
    { codigo: '5006307', nome: 'Naviraí', regiao: 'Centro-Oeste' },
    { codigo: '5002407', nome: 'Nova Andradina', regiao: 'Centro-Oeste' },
    { codigo: '5002902', nome: 'Aquidauana', regiao: 'Centro-Oeste' },
    { codigo: '5004502', nome: 'Paranaíba', regiao: 'Centro-Oeste' },
    { codigo: '5001506', nome: 'Amambai', regiao: 'Centro-Oeste' },
    { codigo: '5005705', nome: 'Ribas do Rio Pardo', regiao: 'Centro-Oeste' },
    { codigo: '5006604', nome: 'São Gabriel do Oeste', regiao: 'Centro-Oeste' },
  ],
  MG: [
    { codigo: '3106200', nome: 'Belo Horizonte', regiao: 'Sudeste' },
    { codigo: '3157807', nome: 'Uberlândia', regiao: 'Sudeste' },
    { codigo: '3170107', nome: 'Contagem', regiao: 'Sudeste' },
    { codigo: '3106705', nome: 'Juiz de Fora', regiao: 'Sudeste' },
    { codigo: '3118601', nome: 'Betim', regiao: 'Sudeste' },
    { codigo: '3148103', nome: 'Montes Claros', regiao: 'Sudeste' },
    { codigo: '3151800', nome: 'Ribeirão das Neves', regiao: 'Sudeste' },
    { codigo: '3169901', nome: 'Uberaba', regiao: 'Sudeste' },
    { codigo: '3129805', nome: 'Governador Valadares', regiao: 'Sudeste' },
    { codigo: '3126109', nome: 'Ipatinga', regiao: 'Sudeste' },
    { codigo: '3143302', nome: 'Sete Lagoas', regiao: 'Sudeste' },
    { codigo: '3131304', nome: 'Divinópolis', regiao: 'Sudeste' },
    { codigo: '3103504', nome: 'Barbacena', regiao: 'Sudeste' },
    { codigo: '3136702', nome: 'Poços de Caldas', regiao: 'Sudeste' },
  ],
  PA: [
    { codigo: '1501402', nome: 'Belém', regiao: 'Norte' },
    { codigo: '1504208', nome: 'Santarém', regiao: 'Norte' },
    { codigo: '1500802', nome: 'Ananindeua', regiao: 'Norte' },
    { codigo: '1506807', nome: 'Marabá', regiao: 'Norte' },
    { codigo: '1505502', nome: 'Castanhal', regiao: 'Norte' },
    { codigo: '1503309', nome: 'Parauapebas', regiao: 'Norte' },
    { codigo: '1502400', nome: 'Abaetetuba', regiao: 'Norte' },
    { codigo: '1501303', nome: 'Barcarena', regiao: 'Norte' },
    { codigo: '1504000', nome: 'Altamira', regiao: 'Norte' },
    { codigo: '1503002', nome: 'Tucuruí', regiao: 'Norte' },
    { codigo: '1501501', nome: 'Redenção', regiao: 'Norte' },
    { codigo: '1505304', nome: 'Bragança', regiao: 'Norte' },
  ],
  PB: [
    { codigo: '2507507', nome: 'João Pessoa', regiao: 'Nordeste' },
    { codigo: '2504009', nome: 'Campina Grande', regiao: 'Nordeste' },
    { codigo: '2503209', nome: 'Santa Rita', regiao: 'Nordeste' },
    { codigo: '2513708', nome: 'Patos', regiao: 'Nordeste' },
    { codigo: '2500409', nome: 'Bayeux', regiao: 'Nordeste' },
    { codigo: '2506001', nome: 'Sousa', regiao: 'Nordeste' },
    { codigo: '2503704', nome: 'Cajazeiras', regiao: 'Nordeste' },
    { codigo: '2501804', nome: 'Cabedelo', regiao: 'Nordeste' },
    { codigo: '2508901', nome: 'Guarabira', regiao: 'Nordeste' },
    { codigo: '2512502', nome: 'Monteiro', regiao: 'Nordeste' },
    { codigo: '2504405', nome: 'Catolé do Rocha', regiao: 'Nordeste' },
    { codigo: '2500607', nome: 'Conceição', regiao: 'Nordeste' },
  ],
  PR: [
    { codigo: '4106902', nome: 'Curitiba', regiao: 'Sul' },
    { codigo: '4115200', nome: 'Londrina', regiao: 'Sul' },
    { codigo: '4108304', nome: 'Maringá', regiao: 'Sul' },
    { codigo: '4125506', nome: 'São José dos Pinhais', regiao: 'Sul' },
    { codigo: '4105805', nome: 'Cascavel', regiao: 'Sul' },
    { codigo: '4104209', nome: 'Foz do Iguaçu', regiao: 'Sul' },
    { codigo: '4113700', nome: 'Ponta Grossa', regiao: 'Sul' },
    { codigo: '4119905', nome: 'Toledo', regiao: 'Sul' },
    { codigo: '4101804', nome: 'Apucarana', regiao: 'Sul' },
    { codigo: '4102109', nome: 'Araucária', regiao: 'Sul' },
    { codigo: '4127700', nome: 'Umuarama', regiao: 'Sul' },
    { codigo: '4118402', nome: 'Campo Mourão', regiao: 'Sul' },
    { codigo: '4119509', nome: 'Pinhais', regiao: 'Sul' },
    { codigo: '4101408', nome: 'Cambé', regiao: 'Sul' },
  ],
  PE: [
    { codigo: '2611606', nome: 'Recife', regiao: 'Nordeste' },
    { codigo: '2604106', nome: 'Jaboatão dos Guararapes', regiao: 'Nordeste' },
    { codigo: '2602902', nome: 'Olinda', regiao: 'Nordeste' },
    { codigo: '2606006', nome: 'Caruaru', regiao: 'Nordeste' },
    { codigo: '2609600', nome: 'Petrolina', regiao: 'Nordeste' },
    { codigo: '2610707', nome: 'Paulista', regiao: 'Nordeste' },
    { codigo: '2600054', nome: 'Cabo de Santo Agostinho', regiao: 'Nordeste' },
    { codigo: '2607905', nome: 'Camaragibe', regiao: 'Nordeste' },
    { codigo: '2606808', nome: 'Garanhuns', regiao: 'Nordeste' },
    { codigo: '2611101', nome: 'Vitória de Santo Antão', regiao: 'Nordeste' },
    { codigo: '2606204', nome: 'Igarassu', regiao: 'Nordeste' },
    { codigo: '2602201', nome: 'São Lourenço da Mata', regiao: 'Nordeste' },
    { codigo: '2601708', nome: 'Araripina', regiao: 'Nordeste' },
  ],
  PI: [
    { codigo: '2211001', nome: 'Teresina', regiao: 'Nordeste' },
    { codigo: '2207702', nome: 'Parnaíba', regiao: 'Nordeste' },
    { codigo: '2200200', nome: 'Altos', regiao: 'Nordeste' },
    { codigo: '2208007', nome: 'Picos', regiao: 'Nordeste' },
    { codigo: '2201208', nome: 'Barras', regiao: 'Nordeste' },
    { codigo: '2202206', nome: 'Campo Maior', regiao: 'Nordeste' },
    { codigo: '2209500', nome: 'Piripiri', regiao: 'Nordeste' },
    { codigo: '2200408', nome: 'Floriano', regiao: 'Nordeste' },
    { codigo: '2202305', nome: 'Canto do Buriti', regiao: 'Nordeste' },
    { codigo: '2201919', nome: 'Buriti dos Lopes', regiao: 'Nordeste' },
    { codigo: '2202107', nome: 'Pedro II', regiao: 'Nordeste' },
    { codigo: '2206504', nome: 'Oeiras', regiao: 'Nordeste' },
  ],
  RJ: [
    { codigo: '3304557', nome: 'Rio de Janeiro', regiao: 'Sudeste' },
    { codigo: '3304904', nome: 'São Gonçalo', regiao: 'Sudeste' },
    { codigo: '3303500', nome: 'Nova Iguaçu', regiao: 'Sudeste' },
    { codigo: '3303302', nome: 'Duque de Caxias', regiao: 'Sudeste' },
    { codigo: '3301702', nome: 'Campos dos Goytacazes', regiao: 'Sudeste' },
    { codigo: '3302504', nome: 'Belford Roxo', regiao: 'Sudeste' },
    { codigo: '3301009', nome: 'Cabo Frio', regiao: 'Sudeste' },
    { codigo: '3302405', nome: 'Petrópolis', regiao: 'Sudeste' },
    { codigo: '3302207', nome: 'Volta Redonda', regiao: 'Sudeste' },
    { codigo: '3300456', nome: 'Macae', regiao: 'Sudeste' },
    { codigo: '3302603', nome: 'Niterói', regiao: 'Sudeste' },
    { codigo: '3304204', nome: 'Resende', regiao: 'Sudeste' },
    { codigo: '3300209', nome: 'Barra Mansa', regiao: 'Sudeste' },
    { codigo: '3305109', nome: 'Teresópolis', regiao: 'Sudeste' },
  ],
  RN: [
    { codigo: '2408102', nome: 'Natal', regiao: 'Nordeste' },
    { codigo: '2403205', nome: 'Mossoró', regiao: 'Nordeste' },
    { codigo: '2402603', nome: 'Parnamirim', regiao: 'Nordeste' },
    { codigo: '2402207', nome: 'São Gonçalo do Amarante', regiao: 'Nordeste' },
    { codigo: '2401407', nome: 'Macaíba', regiao: 'Nordeste' },
    { codigo: '2403601', nome: 'Ceará-Mirim', regiao: 'Nordeste' },
    { codigo: '2402009', nome: 'Caicó', regiao: 'Nordeste' },
    { codigo: '2407104', nome: 'Assu', regiao: 'Nordeste' },
    { codigo: '2401209', nome: 'Currais Novos', regiao: 'Nordeste' },
    { codigo: '2403254', nome: 'Pau dos Ferros', regiao: 'Nordeste' },
    { codigo: '2400102', nome: 'Santa Cruz', regiao: 'Nordeste' },
    { codigo: '2402702', nome: 'Nova Cruz', regiao: 'Nordeste' },
  ],
  RS: [
    { codigo: '4314902', nome: 'Porto Alegre', regiao: 'Sul' },
    { codigo: '4313407', nome: 'Caxias do Sul', regiao: 'Sul' },
    { codigo: '4305108', nome: 'Canoas', regiao: 'Sul' },
    { codigo: '4316907', nome: 'Santa Maria', regiao: 'Sul' },
    { codigo: '4309309', nome: 'Novo Hamburgo', regiao: 'Sul' },
    { codigo: '4323002', nome: 'Gravataí', regiao: 'Sul' },
    { codigo: '4304606', nome: 'Passo Fundo', regiao: 'Sul' },
    { codigo: '4320800', nome: 'São Leopoldo', regiao: 'Sul' },
    { codigo: '4314407', nome: 'Pelotas', regiao: 'Sul' },
    { codigo: '4323309', nome: 'Uruguaiana', regiao: 'Sul' },
    { codigo: '4318707', nome: 'Santa Cruz do Sul', regiao: 'Sul' },
    { codigo: '4309200', nome: 'Esteio', regiao: 'Sul' },
    { codigo: '4320008', nome: 'Viamão', regiao: 'Sul' },
    { codigo: '4302108', nome: 'Bento Gonçalves', regiao: 'Sul' },
  ],
  RO: [
    { codigo: '1100205', nome: 'Porto Velho', regiao: 'Norte' },
    { codigo: '1100304', nome: 'Ji-Paraná', regiao: 'Norte' },
    { codigo: '1100601', nome: 'Ariquemes', regiao: 'Norte' },
    { codigo: '1101500', nome: 'Vilhena', regiao: 'Norte' },
    { codigo: '1101708', nome: 'Cacoal', regiao: 'Norte' },
    { codigo: '1100122', nome: 'Rolim de Moura', regiao: 'Norte' },
    { codigo: '1100608', nome: 'Ouro Preto do Oeste', regiao: 'Norte' },
    { codigo: '1100924', nome: 'Jaru', regiao: 'Norte' },
    { codigo: '1101302', nome: 'Guajará-Mirim', regiao: 'Norte' },
    { codigo: '1100403', nome: 'Pimenta Bueno', regiao: 'Norte' },
    { codigo: '1101807', nome: 'Machadinho D\'Oeste', regiao: 'Norte' },
    { codigo: '1100031', nome: 'Nova Mamoré', regiao: 'Norte' },
  ],
  RR: [
    { codigo: '1400100', nome: 'Boa Vista', regiao: 'Norte' },
    { codigo: '1400209', nome: 'Rorainópolis', regiao: 'Norte' },
    { codigo: '1400308', nome: 'Caracaraí', regiao: 'Norte' },
    { codigo: '1400704', nome: 'Mucajaí', regiao: 'Norte' },
    { codigo: '1400407', nome: 'Alto Alegre', regiao: 'Norte' },
    { codigo: '1400506', nome: 'Bonfim', regiao: 'Norte' },
    { codigo: '1400027', nome: 'Cantá', regiao: 'Norte' },
    { codigo: '1400175', nome: 'Pacaraima', regiao: 'Norte' },
    { codigo: '1400233', nome: 'Normandia', regiao: 'Norte' },
    { codigo: '1400605', nome: 'Iracema', regiao: 'Norte' },
    { codigo: '1400282', nome: 'Amajari', regiao: 'Norte' },
    { codigo: '1400159', nome: 'São João da Baliza', regiao: 'Norte' },
  ],
  SC: [
    { codigo: '4205407', nome: 'Florianópolis', regiao: 'Sul' },
    { codigo: '4208203', nome: 'Joinville', regiao: 'Sul' },
    { codigo: '4202404', nome: 'Blumenau', regiao: 'Sul' },
    { codigo: '4211305', nome: 'São José', regiao: 'Sul' },
    { codigo: '4216602', nome: 'Criciúma', regiao: 'Sul' },
    { codigo: '4209102', nome: 'Chapecó', regiao: 'Sul' },
    { codigo: '4204606', nome: 'Lages', regiao: 'Sul' },
    { codigo: '4204200', nome: 'Itajaí', regiao: 'Sul' },
    { codigo: '4208906', nome: 'Balneário Camboriú', regiao: 'Sul' },
    { codigo: '4214804', nome: 'Palhoça', regiao: 'Sul' },
    { codigo: '4201208', nome: 'Brusque', regiao: 'Sul' },
    { codigo: '4211906', nome: 'Tubarão', regiao: 'Sul' },
    { codigo: '4203204', nome: 'Concórdia', regiao: 'Sul' },
    { codigo: '4218202', nome: 'Jaraguá do Sul', regiao: 'Sul' },
  ],
  SP: [
    { codigo: '3550308', nome: 'São Paulo', regiao: 'Sudeste' },
    { codigo: '3548708', nome: 'Campinas', regiao: 'Sudeste' },
    { codigo: '3509502', nome: 'Guarulhos', regiao: 'Sudeste' },
    { codigo: '3524407', nome: 'Ribeirão Preto', regiao: 'Sudeste' },
    { codigo: '3541406', nome: 'São Bernardo do Campo', regiao: 'Sudeste' },
    { codigo: '3541000', nome: 'Santo André', regiao: 'Sudeste' },
    { codigo: '3523102', nome: 'Osasco', regiao: 'Sudeste' },
    { codigo: '3506003', nome: 'Sorocaba', regiao: 'Sudeste' },
    { codigo: '3526902', nome: 'São José dos Campos', regiao: 'Sudeste' },
    { codigo: '3548906', nome: 'Franca', regiao: 'Sudeste' },
    { codigo: '3502502', nome: 'Araçatuba', regiao: 'Sudeste' },
    { codigo: '3543402', nome: 'São José do Rio Preto', regiao: 'Sudeste' },
    { codigo: '3534401', nome: 'Piracicaba', regiao: 'Sudeste' },
    { codigo: '3503203', nome: 'Bauru', regiao: 'Sudeste' },
    { codigo: '3516200', nome: 'Jundiaí', regiao: 'Sudeste' },
    { codigo: '3508405', nome: 'Presidente Prudente', regiao: 'Sudeste' },
    { codigo: '3535507', nome: 'Americana', regiao: 'Sudeste' },
  ],
  SE: [
    { codigo: '2800308', nome: 'Aracaju', regiao: 'Nordeste' },
    { codigo: '2804805', nome: 'Nossa Senhora do Socorro', regiao: 'Nordeste' },
    { codigo: '2803500', nome: 'Lagarto', regiao: 'Nordeste' },
    { codigo: '2802908', nome: 'Itabaiana', regiao: 'Nordeste' },
    { codigo: '2801504', nome: 'Estância', regiao: 'Nordeste' },
    { codigo: '2802108', nome: 'São Cristóvão', regiao: 'Nordeste' },
    { codigo: '2800209', nome: 'Tobias Barreto', regiao: 'Nordeste' },
    { codigo: '2800605', nome: 'Capela', regiao: 'Nordeste' },
    { codigo: '2804706', nome: 'Santo Amaro das Brotas', regiao: 'Nordeste' },
    { codigo: '2801108', nome: 'Propriá', regiao: 'Nordeste' },
    { codigo: '2802600', nome: 'Simão Dias', regiao: 'Nordeste' },
    { codigo: '2801207', nome: 'Riachão do Dantas', regiao: 'Nordeste' },
  ],
  TO: [
    { codigo: '1721000', nome: 'Palmas', regiao: 'Norte' },
    { codigo: '1718204', nome: 'Araguaína', regiao: 'Norte' },
    { codigo: '1701108', nome: 'Gurupi', regiao: 'Norte' },
    { codigo: '1716105', nome: 'Porto Nacional', regiao: 'Norte' },
    { codigo: '1707008', nome: 'Paraíso do Tocantins', regiao: 'Norte' },
    { codigo: '1700407', nome: 'Colinas do Tocantins', regiao: 'Norte' },
    { codigo: '1709500', nome: 'Guaraí', regiao: 'Norte' },
    { codigo: '1712100', nome: 'Tocantinópolis', regiao: 'Norte' },
    { codigo: '1706109', nome: 'Miracema do Tocantins', regiao: 'Norte' },
    { codigo: '1708204', nome: 'Pedro Afonso', regiao: 'Norte' },
    { codigo: '1703307', nome: 'Augustinópolis', regiao: 'Norte' },
    { codigo: '1721208', nome: 'Dianópolis', regiao: 'Norte' },
  ],
};

const cfops = [
  { codigo: '1101', descricao: 'Compra para industrialização', tipo: 'ENTRADA' },
  { codigo: '1102', descricao: 'Compra para comercialização', tipo: 'ENTRADA' },
  { codigo: '1111', descricao: 'Compra para industrialização de mercadoria recebida anteriormente em consignação industrial', tipo: 'ENTRADA' },
  { codigo: '1113', descricao: 'Compra para comercialização de mercadoria recebida anteriormente em consignação mercantil', tipo: 'ENTRADA' },
  { codigo: '1151', descricao: 'Transferência de produção para comercialização', tipo: 'ENTRADA' },
  { codigo: '1152', descricao: 'Transferência de produção para industrialização', tipo: 'ENTRADA' },
  { codigo: '1201', descricao: 'Devolução de venda de produção própria', tipo: 'ENTRADA' },
  { codigo: '1202', descricao: 'Devolução de venda de mercadoria adquirida ou recebida de terceiros', tipo: 'ENTRADA' },
  { codigo: '1251', descricao: 'Compra de energia elétrica', tipo: 'ENTRADA' },
  { codigo: '1252', descricao: 'Compra de combustível ou lubrificante', tipo: 'ENTRADA' },
  { codigo: '1253', descricao: 'Compra de serviço de comunicação', tipo: 'ENTRADA' },
  { codigo: '1254', descricao: 'Compra de serviço de transporte', tipo: 'ENTRADA' },
  { codigo: '1301', descricao: 'Entrada de mercadoria em consignação industrial', tipo: 'ENTRADA' },
  { codigo: '1302', descricao: 'Entrada de mercadoria em consignação mercantil', tipo: 'ENTRADA' },
  { codigo: '1401', descricao: 'Retorno de produção de terceiro', tipo: 'ENTRADA' },
  { codigo: '1403', descricao: 'Retorno de mercadoria enviada em consignação industrial', tipo: 'ENTRADA' },
  { codigo: '1406', descricao: 'Retorno de mercadoria enviada em consignação mercantil', tipo: 'ENTRADA' },
  { codigo: '1501', descricao: 'Entrada de bem do ativo imobilizado', tipo: 'ENTRADA' },
  { codigo: '1551', descricao: 'Compra de bem para o ativo imobilizado', tipo: 'ENTRADA' },
  { codigo: '1601', descricao: 'Recebimento por doação de produção própria', tipo: 'ENTRADA' },
  { codigo: '1602', descricao: 'Recebimento por doação de mercadoria adquirida de terceiros', tipo: 'ENTRADA' },
  { codigo: '1651', descricao: 'Compra de material de uso e consumo', tipo: 'ENTRADA' },
  { codigo: '1901', descricao: 'Outra entrada de mercadoria ou prestação de serviço', tipo: 'ENTRADA' },
  { codigo: '1902', descricao: 'Entrada de mercadoria em bonificação', tipo: 'ENTRADA' },
  { codigo: '1903', descricao: 'Entrada de mercadoria em demonstração', tipo: 'ENTRADA' },
  { codigo: '1904', descricao: 'Retorno de mercadoria em demonstração', tipo: 'ENTRADA' },
  { codigo: '1905', descricao: 'Entrada de mercadoria em brinde', tipo: 'ENTRADA' },
  { codigo: '1906', descricao: 'Entrada de mercadoria em amostra grátis', tipo: 'ENTRADA' },
  { codigo: '1907', descricao: 'Retorno de mercadoria em bonificação', tipo: 'ENTRADA' },
  { codigo: '1910', descricao: 'Entrada de mercadoria em garantia/substituição', tipo: 'ENTRADA' },
  { codigo: '1911', descricao: 'Entrada de inservíveis/sucata', tipo: 'ENTRADA' },
  { codigo: '1912', descricao: 'Entrada de vasilhame/embalagem', tipo: 'ENTRADA' },
  { codigo: '1913', descricao: 'Entrada de mercadoria por arrematação', tipo: 'ENTRADA' },
  { codigo: '1914', descricao: 'Entrada de mercadoria por adjudicação', tipo: 'ENTRADA' },
  { codigo: '1915', descricao: 'Entrada de mercadoria por dação em pagamento', tipo: 'ENTRADA' },
  { codigo: '1916', descricao: 'Entrada decorrente de importação', tipo: 'ENTRADA' },
  { codigo: '1917', descricao: 'Entrada de mercadoria por furto/roubo (ressarcimento)', tipo: 'ENTRADA' },
  { codigo: '1918', descricao: 'Entrada de mercadoria por perecimento/extraviada (ressarcimento)', tipo: 'ENTRADA' },
  { codigo: '1919', descricao: 'Entrada de mercadoria recibida do exterior', tipo: 'ENTRADA' },
  { codigo: '1920', descricao: 'Entrada de mercadoria sob regime drawback', tipo: 'ENTRADA' },
  { codigo: '1921', descricao: 'Entrada de mercadoria em regime de entreposto aduaneiro', tipo: 'ENTRADA' },
  { codigo: '2101', descricao: 'Devolução de compra para industrialização', tipo: 'SAIDA' },
  { codigo: '2102', descricao: 'Devolução de compra para comercialização', tipo: 'SAIDA' },
  { codigo: '2201', descricao: 'Retorno de consignação industrial', tipo: 'SAIDA' },
  { codigo: '2202', descricao: 'Retorno de consignação mercantil', tipo: 'SAIDA' },
  { codigo: '2251', descricao: 'Retorno de compra de energia elétrica', tipo: 'SAIDA' },
  { codigo: '2301', descricao: 'Venda de produção própria', tipo: 'SAIDA' },
  { codigo: '2401', descricao: 'Venda de mercadoria adquirida de terceiros', tipo: 'SAIDA' },
  { codigo: '2501', descricao: 'Venda de bem do ativo imobilizado', tipo: 'SAIDA' },
  { codigo: '2551', descricao: 'Venda de material de uso e consumo', tipo: 'SAIDA' },
  { codigo: '2601', descricao: 'Remessa para consignação industrial', tipo: 'SAIDA' },
  { codigo: '2602', descricao: 'Remessa para consignação mercantil', tipo: 'SAIDA' },
  { codigo: '2603', descricao: 'Remessa para industrialização por terceiro', tipo: 'SAIDA' },
  { codigo: '2651', descricao: 'Remessa de energia elétrica', tipo: 'SAIDA' },
  { codigo: '2652', descricao: 'Remessa de combustível ou lubrificante', tipo: 'SAIDA' },
  { codigo: '2653', descricao: 'Remessa de serviço de comunicação', tipo: 'SAIDA' },
  { codigo: '2654', descricao: 'Remessa de serviço de transporte', tipo: 'SAIDA' },
  { codigo: '2701', descricao: 'Remessa de bem do ativo imobilizado para uso de terceiro', tipo: 'SAIDA' },
  { codigo: '2901', descricao: 'Outra saída de mercadoria ou prestação de serviço', tipo: 'SAIDA' },
  { codigo: '2902', descricao: 'Remessa de mercadoria em bonificação', tipo: 'SAIDA' },
  { codigo: '2903', descricao: 'Remessa de mercadoria em demonstração', tipo: 'SAIDA' },
  { codigo: '2904', descricao: 'Remessa de mercadoria em brinde', tipo: 'SAIDA' },
  { codigo: '2905', descricao: 'Remessa de mercadoria em amostra grátis', tipo: 'SAIDA' },
  { codigo: '2906', descricao: 'Remessa de mercadoria em garantia/substituição', tipo: 'SAIDA' },
  { codigo: '2907', descricao: 'Remessa de inservíveis/sucata', tipo: 'SAIDA' },
  { codigo: '2908', descricao: 'Remessa de vasilhame/embalagem', tipo: 'SAIDA' },
  { codigo: '2909', descricao: 'Remessa de mercadoria por arrematação', tipo: 'SAIDA' },
  { codigo: '2910', descricao: 'Remessa de mercadoria por adjudicação', tipo: 'SAIDA' },
  { codigo: '2911', descricao: 'Remessa de mercadoria por dação em pagamento', tipo: 'SAIDA' },
  { codigo: '2912', descricao: 'Remessa de mercadoria em regime drawback', tipo: 'SAIDA' },
  { codigo: '2913', descricao: 'Remessa de mercadoria em regime de entreposto aduaneiro', tipo: 'SAIDA' },
  { codigo: '2914', descricao: 'Remessa para exportação', tipo: 'SAIDA' },
  { codigo: '2915', descricao: 'Remessa decorrente de exportação', tipo: 'SAIDA' },
  { codigo: '2916', descricao: 'Saída de mercadoria por furto/roubo', tipo: 'SAIDA' },
  { codigo: '2917', descricao: 'Saída de mercadoria por perecimento/extraviada', tipo: 'SAIDA' },
  { codigo: '2918', descricao: 'Remessa para depósito fechado', tipo: 'SAIDA' },
  { codigo: '2919', descricao: 'Remessa de mercadoria pelo fato de ter sido recebida indevidamente', tipo: 'SAIDA' },
  { codigo: '2920', descricao: 'Remessa para depósito em armazém geral', tipo: 'SAIDA' },
  { codigo: '2921', descricao: 'Remessa de mercadoria de terceiro para depósito fechado', tipo: 'SAIDA' },
  { codigo: '2922', descricao: 'Remessa de bem do ativo imobilizado para depósito fechado', tipo: 'SAIDA' },
  { codigo: '2923', descricao: 'Remessa de mercadoria para entrega futura', tipo: 'SAIDA' },
  { codigo: '2924', descricao: 'Remessa de mercadoria por contrato de comodato', tipo: 'SAIDA' },
  { codigo: '3101', descricao: 'Compra para industrialização (não contribuinte)', tipo: 'ENTRADA' },
  { codigo: '3102', descricao: 'Compra para comercialização (não contribuinte)', tipo: 'ENTRADA' },
  { codigo: '3201', descricao: 'Devolução de venda (não contribuinte)', tipo: 'ENTRADA' },
  { codigo: '3202', descricao: 'Devolução de venda de mercadoria adquirida (não contribuinte)', tipo: 'ENTRADA' },
  { codigo: '5101', descricao: 'Venda de produção própria (contribuinte fora do estado)', tipo: 'SAIDA' },
  { codigo: '5102', descricao: 'Venda de mercadoria adquirida (contribuinte fora do estado)', tipo: 'SAIDA' },
  { codigo: '5401', descricao: 'Venda de produção própria (contribuinte dentro do estado)', tipo: 'SAIDA' },
  { codigo: '5402', descricao: 'Venda de mercadoria adquirida (contribuinte dentro do estado)', tipo: 'SAIDA' },
  { codigo: '6101', descricao: 'Venda de produção própria (consumidor final)', tipo: 'SAIDA' },
  { codigo: '6102', descricao: 'Venda de mercadoria adquirida (consumidor final)', tipo: 'SAIDA' },
  { codigo: '6108', descricao: 'Venda de mercadoria adquirida (consumidor final, entrega futura)', tipo: 'SAIDA' },
  { codigo: '6401', descricao: 'Venda de produção própria (consumidor final dentro do estado)', tipo: 'SAIDA' },
  { codigo: '6402', descricao: 'Venda de mercadoria adquirida (consumidor final dentro do estado)', tipo: 'SAIDA' },
  { codigo: '6403', descricao: 'Venda de combustível para consumidor final', tipo: 'SAIDA' },
  { codigo: '6404', descricao: 'Venda de mercadoria em remessa futura', tipo: 'SAIDA' },
];

const ncms = [
  { codigo: '01012100', descricao: 'Cavalos, asnos e muares, reprodutores de raça pura' },
  { codigo: '01022100', descricao: 'Animais vivos da espécie bovina, reprodutores de raça pura' },
  { codigo: '01031000', descricao: 'Animais vivos da espécie suína, reprodutores de raça pura' },
  { codigo: '01051100', descricao: 'Galinhas vivas, reprodutoras e matrizes' },
  { codigo: '02012020', descricao: 'Carnes de bovinos, frescas ou refrigeradas' },
  { codigo: '02021000', descricao: 'Carnes de bovinos, congeladas' },
  { codigo: '02031100', descricao: 'Carnes de suínos, frescas ou refrigeradas' },
  { codigo: '02071200', descricao: 'Carnes de galos/galinhas, congeladas' },
  { codigo: '03021210', descricao: 'Salmões frescos ou refrigerados' },
  { codigo: '03034200', descricao: 'Atuns congelados' },
  { codigo: '04011010', descricao: 'Leite, creme de leite, com teor de gordura <=1%' },
  { codigo: '04021010', descricao: 'Leite em pó, com teor de gordura <=1,5%' },
  { codigo: '04051000', descricao: 'Manteiga' },
  { codigo: '04061010', descricao: 'Queijo fresco (não fermentado)' },
  { codigo: '04072100', descricao: 'Ovos de galinha, frescos' },
  { codigo: '04090000', descricao: 'Mel natural' },
  { codigo: '06021000', descricao: 'Estacas enraizadas e enxertos' },
  { codigo: '06031100', descricao: 'Rosas, cortadas, para buquês' },
  { codigo: '07011000', descricao: 'Batatas (semeadura), frescas ou refrigeradas' },
  { codigo: '07020000', descricao: 'Tomates, frescos ou refrigerados' },
  { codigo: '07031010', descricao: 'Cebolas, frescas ou refrigeradas' },
  { codigo: '07049000', descricao: 'Couves, frescas ou refrigeradas' },
  { codigo: '07061000', descricao: 'Cenouras e nabos, frescos ou refrigerados' },
  { codigo: '07092000', descricao: 'Aspargos, frescos ou refrigerados' },
  { codigo: '07101000', descricao: 'Batatas congeladas' },
  { codigo: '07131000', descricao: 'Ervilhas secas' },
  { codigo: '08030010', descricao: 'Bananas frescas' },
  { codigo: '08043000', descricao: 'Abacaxis frescos' },
  { codigo: '08044000', descricao: 'Abacates frescos' },
  { codigo: '08045010', descricao: 'Goiabas frescas' },
  { codigo: '08051000', descricao: 'Laranjas frescas' },
  { codigo: '08055010', descricao: 'Limões frescos' },
  { codigo: '08061000', descricao: 'Uvas frescas' },
  { codigo: '08081000', descricao: 'Maçãs frescas' },
  { codigo: '08082010', descricao: 'Peras frescas' },
  { codigo: '09011110', descricao: 'Café não torrado, não descafeinado' },
  { codigo: '09012100', descricao: 'Café torrado, não descafeinado' },
  { codigo: '09021000', descricao: 'Chá verde em embalagens <=3kg' },
  { codigo: '09041100', descricao: 'Pimenta (gênero Piper), não triturada' },
  { codigo: '09051000', descricao: 'Baunilha' },
  { codigo: '10019000', descricao: 'Trigo e centeio, exceto para semeadura' },
  { codigo: '10051000', descricao: 'Milho para semeadura' },
  { codigo: '10059010', descricao: 'Milho em grão, exceto para semeadura' },
  { codigo: '10061010', descricao: 'Arroz com casca' },
  { codigo: '10063010', descricao: 'Arroz semibranqueado ou branqueado' },
  { codigo: '11010010', descricao: 'Farinha de trigo' },
  { codigo: '11022000', descricao: 'Farinha de milho' },
  { codigo: '11031100', descricao: 'Sêmola de trigo' },
  { codigo: '11042200', descricao: 'Flocos de aveia' },
  { codigo: '12010000', descricao: 'Soja, mesmo triturada' },
  { codigo: '12051000', descricao: 'Sementes de nabo forrageiro' },
  { codigo: '12081000', descricao: 'Farinha de soja' },
  { codigo: '15071000', descricao: 'Óleo de soja em bruto' },
  { codigo: '15091000', descricao: 'Azeite de oliva virgem' },
  { codigo: '15111000', descricao: 'Óleo de palma em bruto' },
  { codigo: '15121910', descricao: 'Óleo de girassol em bruto' },
  { codigo: '15141910', descricao: 'Óleo de colza em bruto' },
  { codigo: '16010000', descricao: 'Enchidos e produtos semelhantes de carne' },
  { codigo: '16041310', descricao: 'Sardinhas em conserva' },
  { codigo: '17011400', descricao: 'Açúcar de cana em bruto' },
  { codigo: '17019900', descricao: 'Açúcar refinado' },
  { codigo: '17041000', descricao: 'Chicletes' },
  { codigo: '17049010', descricao: 'Confeitos de açúcar' },
  { codigo: '18010000', descricao: 'Cacau inteiro ou partido, cru ou torrado' },
  { codigo: '18031000', descricao: 'Pasta de cacau' },
  { codigo: '18050000', descricao: 'Cacau em pó' },
  { codigo: '18061000', descricao: 'Chocolate em pó' },
  { codigo: '18063110', descricao: 'Chocolate em barras, recheado' },
  { codigo: '19011010', descricao: 'Farinhas lácteas para alimentação infantil' },
  { codigo: '19012000', descricao: 'Misturas para bolos' },
  { codigo: '19021100', descricao: 'Massas alimentícias não cozidas' },
  { codigo: '19041000', descricao: 'Produtos à base de cereais, expandidos' },
  { codigo: '19053100', descricao: 'Biscoitos doces' },
  { codigo: '19053200', descricao: 'Waffles e wafers' },
  { codigo: '19054000', descricao: 'Torradas e produtos semelhantes' },
  { codigo: '20011000', descricao: 'Pepinos conservados em vinagre' },
  { codigo: '20019000', descricao: 'Legumes conservados em vinagre' },
  { codigo: '20021000', descricao: 'Tomates inteiros ou em pedaços' },
  { codigo: '20031000', descricao: 'Cogumelos preparados' },
  { codigo: '20041000', descricao: 'Batatas preparadas, congeladas' },
  { codigo: '20052000', descricao: 'Batatas preparadas ou conservadas' },
  { codigo: '20079910', descricao: 'Doces de frutas em pasta' },
  { codigo: '20081100', descricao: 'Amendoins preparados' },
  { codigo: '20081910', descricao: 'Castanhas preparadas' },
  { codigo: '20094100', descricao: 'Suco de abacaxi' },
  { codigo: '20097100', descricao: 'Suco de maçã' },
  { codigo: '20101000', descricao: 'Suco de laranja congelado' },
  { codigo: '21011110', descricao: 'Extratos de café' },
  { codigo: '21021010', descricao: 'Leveduras vivas' },
  { codigo: '21031010', descricao: 'Molho de soja' },
  { codigo: '21032010', descricao: 'Ketchup e outros molhos de tomate' },
  { codigo: '21033010', descricao: 'Farinha de mostarda' },
  { codigo: '21039010', descricao: 'Maionese' },
  { codigo: '21041010', descricao: 'Caldos e sopas preparados' },
  { codigo: '21050010', descricao: 'Sorvetes' },
  { codigo: '21061010', descricao: 'Concentrados de proteínas' },
  { codigo: '21069010', descricao: 'Complementos alimentares' },
  { codigo: '22011000', descricao: 'Águas minerais' },
  { codigo: '22021000', descricao: 'Refrigerantes' },
  { codigo: '22029100', descricao: 'Cerveja sem álcool' },
  { codigo: '22030000', descricao: 'Cerveja de malte' },
  { codigo: '22042100', descricao: 'Vinhos em recipientes <=2L' },
  { codigo: '22043000', descricao: 'Mosto de uva' },
  { codigo: '22082000', descricao: 'Aguardentes de vinho' },
  { codigo: '22083010', descricao: 'Uísque' },
  { codigo: '22084000', descricao: 'Rum' },
  { codigo: '22086000', descricao: 'Vodca' },
  { codigo: '22087000', descricao: 'Licores' },
  { codigo: '22089010', descricao: 'Cachaça' },
  { codigo: '23012010', descricao: 'Farinhas de peixes' },
  { codigo: '23023010', descricao: 'Resíduos de milho' },
  { codigo: '23040010', descricao: 'Torta de soja' },
  { codigo: '23063000', descricao: 'Resíduos de milho para alimentação animal' },
  { codigo: '24011010', descricao: 'Tabaco não manufaturado' },
  { codigo: '24022000', descricao: 'Cigarros' },
  { codigo: '25010010', descricao: 'Sal de cozinha' },
  { codigo: '25231000', descricao: 'Cimentos não pulverizados' },
  { codigo: '25232100', descricao: 'Cimento Portland' },
  { codigo: '27011100', descricao: 'Carvão betuminoso' },
  { codigo: '27101241', descricao: 'Gasolina' },
  { codigo: '27101931', descricao: 'Óleo diesel' },
  { codigo: '27102000', descricao: 'Querosene' },
  { codigo: '27111100', descricao: 'Gás liquefeito de petróleo (GLP)' },
  { codigo: '27112100', descricao: 'Gás natural' },
  { codigo: '27121000', descricao: 'Vaselina' },
  { codigo: '27122000', descricao: 'Parafina' },
  { codigo: '28046100', descricao: 'Silício' },
  { codigo: '28182010', descricao: 'Alumina' },
  { codigo: '28362010', descricao: 'Carbonato de sódio' },
  { codigo: '28365000', descricao: 'Carbonato de cálcio' },
  { codigo: '28470000', descricao: 'Peróxido de hidrogênio (água oxigenada)' },
  { codigo: '29022000', descricao: 'Benzeno' },
  { codigo: '29023000', descricao: 'Tolueno' },
  { codigo: '29024100', descricao: 'Xileno' },
  { codigo: '29051310', descricao: 'Álcool etílico não desnaturado' },
  { codigo: '29152110', descricao: 'Ácido acético' },
  { codigo: '29224100', descricao: 'Lisina' },
  { codigo: '29331910', descricao: 'Dipirona' },
  { codigo: '29349010', descricao: 'Outros compostos heterocíclicos' },
  { codigo: '30021010', descricao: 'Soros e vacinas' },
  { codigo: '30022010', descricao: 'Vacinas para medicina humana' },
  { codigo: '30031000', descricao: 'Medicamentos contendo penicilinas' },
  { codigo: '30032010', descricao: 'Medicamentos contendo antibióticos' },
  { codigo: '30042010', descricao: 'Antibióticos para uso humano' },
  { codigo: '30043210', descricao: 'Medicamentos corticosteroides' },
  { codigo: '30043910', descricao: 'Medicamentos hormonais' },
  { codigo: '30045010', descricao: 'Medicamentos vitamínicos' },
  { codigo: '30049010', descricao: 'Outros medicamentos para uso humano' },
  { codigo: '30059010', descricao: 'Algodão hidrófilo' },
  { codigo: '30061010', descricao: 'Categutes estéreis' },
  { codigo: '32011000', descricao: 'Extrato de quebracho' },
  { codigo: '32012000', descricao: 'Extrato de acácia' },
  { codigo: '32041610', descricao: 'Corantes reativos' },
  { codigo: '32041710', descricao: 'Corantes orgânicos sintéticos' },
  { codigo: '32041910', descricao: 'Outros corantes orgânicos' },
  { codigo: '32082010', descricao: 'Tintas e vernizes' },
  { codigo: '32091010', descricao: 'Tintas à base de polímeros acrílicos' },
  { codigo: '32100010', descricao: 'Outras tintas e vernizes' },
  { codigo: '32131000', descricao: 'Tintas para pintura artística' },
  { codigo: '32141010', descricao: 'Mástiques e cimentos de vidraceiro' },
  { codigo: '33030010', descricao: 'Perfumes (extratos)' },
  { codigo: '33041000', descricao: 'Produtos de maquiagem para lábios' },
  { codigo: '33042010', descricao: 'Produtos de maquiagem para olhos' },
  { codigo: '33043000', descricao: 'Produtos para manicuros e pedicuros' },
  { codigo: '33049910', descricao: 'Produtos de beleza ou maquiagem' },
  { codigo: '33051000', descricao: 'Xampus' },
  { codigo: '33053000', descricao: 'Laquês para o cabelo' },
  { codigo: '33059000', descricao: 'Outros preparados capilares' },
  { codigo: '33061000', descricao: 'Dentifrícios' },
  { codigo: '33071000', descricao: 'Preparados para barbear' },
  { codigo: '33072010', descricao: 'Desodorantes' },
  { codigo: '33073010', descricao: 'Sais de banho' },
  { codigo: '33074100', descricao: 'Incensos e preparados odoríferos' },
  { codigo: '34011110', descricao: 'Sabões de toucador' },
  { codigo: '34012010', descricao: 'Sabões em flocos' },
  { codigo: '34021110', descricao: 'Sabões de uso doméstico' },
  { codigo: '34022000', descricao: 'Detergentes líquidos' },
  { codigo: '34029010', descricao: 'Outros detergentes' },
  { codigo: '34039900', descricao: 'Lubrificantes sintéticos' },
  { codigo: '35030010', descricao: 'Gelatinas' },
  { codigo: '35051000', descricao: 'Dextrina e outros amidos modificados' },
  { codigo: '35061000', descricao: 'Colas e adesivos' },
  { codigo: '37013010', descricao: 'Filmes fotográficos' },
  { codigo: '38021010', descricao: 'Carvão ativado' },
  { codigo: '38081010', descricao: 'Inseticidas' },
  { codigo: '38084010', descricao: 'Fungicidas' },
  { codigo: '38089110', descricao: 'Herbicidas' },
  { codigo: '38101010', descricao: 'Decapantes para metais' },
  { codigo: '38151110', descricao: 'Catalisadores' },
  { codigo: '38160010', descricao: 'Cimentos refratários' },
  { codigo: '38220010', descricao: 'Reagentes de diagnóstico' },
  { codigo: '38231910', descricao: 'Ácidos graxos' },
  { codigo: '38241000', descricao: 'Aglutinantes preparados' },
  { codigo: '38245000', descricao: 'Argamassas e concretos' },
  { codigo: '38249910', descricao: 'Preparações químicas' },
  { codigo: '39011010', descricao: 'Polietileno' },
  { codigo: '39021010', descricao: 'Polipropileno' },
  { codigo: '39031110', descricao: 'Poliestireno' },
  { codigo: '39041010', descricao: 'PVC não plastificado' },
  { codigo: '39042210', descricao: 'PVC plastificado' },
  { codigo: '39069010', descricao: 'Outros polímeros acrílicos' },
  { codigo: '39074010', descricao: 'Policarbonatos' },
  { codigo: '39076010', descricao: 'PET' },
  { codigo: '39081010', descricao: 'Poliamidas' },
  { codigo: '39095010', descricao: 'Poliuretanos' },
  { codigo: '39151000', descricao: 'Desperdícios de polietileno' },
  { codigo: '39162010', descricao: 'Perfis de PVC' },
  { codigo: '39172110', descricao: 'Tubos de polietileno' },
  { codigo: '39173010', descricao: 'Mangueiras de plástico' },
  { codigo: '39174010', descricao: 'Conexões de plástico' },
  { codigo: '39201010', descricao: 'Filmes de polietileno' },
  { codigo: '39202010', descricao: 'Filmes de polipropileno' },
  { codigo: '39204310', descricao: 'Películas de PVC' },
  { codigo: '39204910', descricao: 'Chapas de PVC' },
  { codigo: '39211110', descricao: 'Chapas de poliestireno' },
  { codigo: '39211910', descricao: 'Chapas de poliuretano' },
  { codigo: '39219010', descricao: 'Outras chapas plásticas' },
  { codigo: '39221010', descricao: 'Banheiras e boxes de plástico' },
  { codigo: '39231010', descricao: 'Caixas e engradados de plástico' },
  { codigo: '39232110', descricao: 'Sacos de polietileno' },
  { codigo: '39233010', descricao: 'Garrafas de plástico' },
  { codigo: '39235000', descricao: 'Tampas de plástico' },
  { codigo: '39239010', descricao: 'Outros artigos de plástico' },
  { codigo: '39241010', descricao: 'Talheres de plástico' },
  { codigo: '39249010', descricao: 'Artigos de higiene de plástico' },
  { codigo: '39251000', descricao: 'Reservatórios de plástico' },
  { codigo: '39261010', descricao: 'Artigos de escritório de plástico' },
  { codigo: '39262010', descricao: 'Vestuário de plástico' },
  { codigo: '39269010', descricao: 'Outros artigos de plástico' },
  { codigo: '40111010', descricao: 'Pneus novos para automóveis' },
  { codigo: '40112010', descricao: 'Pneus novos para ônibus e caminhões' },
  { codigo: '40114000', descricao: 'Pneus para motocicletas' },
  { codigo: '40115000', descricao: 'Pneus para bicicletas' },
  { codigo: '40116200', descricao: 'Pneus para máquinas agrícolas' },
  { codigo: '40117000', descricao: 'Pneus para máquinas de construção' },
  { codigo: '40131010', descricao: 'Câmaras de borracha' },
  { codigo: '40151910', descricao: 'Luvas de borracha' },
  { codigo: '40169310', descricao: 'Guarnições de borracha' },
  { codigo: '40169910', descricao: 'Outras obras de borracha' },
  { codigo: '41041110', descricao: 'Couros e peles de bovinos' },
  { codigo: '41071210', descricao: 'Couro curtido ao cromo' },
  { codigo: '41132000', descricao: 'Couro de suínos' },
  { codigo: '42021100', descricao: 'Malas e pastas de couro' },
  { codigo: '42022210', descricao: 'Bolsas de couro' },
  { codigo: '42031010', descricao: 'Artigos de vestuário de couro' },
  { codigo: '42032100', descricao: 'Luvas de couro' },
  { codigo: '42032900', descricao: 'Luvas de couro para esporte' },
  { codigo: '42034000', descricao: 'Cintos de couro' },
  { codigo: '42050010', descricao: 'Outras obras de couro' },
  { codigo: '43031010', descricao: 'Artigos de vestuário de peles' },
  { codigo: '44031000', descricao: 'Madeira em bruto tratada' },
  { codigo: '44071000', descricao: 'Madeira serrada de pinho' },
  { codigo: '44072200', descricao: 'Madeira serrada de virola' },
  { codigo: '44079100', descricao: 'Madeira serrada de carvalho' },
  { codigo: '44079500', descricao: 'Madeira serrada de freijó' },
  { codigo: '44081010', descricao: 'Folhas para fachadas' },
  { codigo: '44091010', descricao: 'Perfis de madeira' },
  { codigo: '44101110', descricao: 'Painéis de partículas de madeira' },
  { codigo: '44111210', descricao: 'Painéis de fibras de média densidade (MDF)' },
  { codigo: '44119210', descricao: 'Outros painéis de fibras' },
  { codigo: '44121000', descricao: 'Compensados de madeira' },
  { codigo: '44130000', descricao: 'Madeira laminada' },
  { codigo: '44140010', descricao: 'Moldura de madeira' },
  { codigo: '44151010', descricao: 'Caixas e paletes de madeira' },
  { codigo: '44152000', descricao: 'Paletes e estrados de madeira' },
  { codigo: '44183000', descricao: 'Portas e janelas de madeira' },
  { codigo: '44184000', descricao: 'Fôrmas para concreto' },
  { codigo: '44185000', descricao: 'Telhas de madeira' },
  { codigo: '44186000', descricao: 'Vigas de madeira' },
  { codigo: '44187100', descricao: 'Pisos de madeira' },
  { codigo: '44187900', descricao: 'Outros pisos de madeira' },
  { codigo: '44190010', descricao: 'Artigos de mesa de madeira' },
  { codigo: '44201000', descricao: 'Esculturas de madeira' },
  { codigo: '44209010', descricao: 'Outras obras de madeira' },
  { codigo: '44211000', descricao: 'Cabides de madeira' },
  { codigo: '45011000', descricao: 'Cortiça natural' },
  { codigo: '45031000', descricao: 'Cortiça natural em blocos' },
  { codigo: '46011000', descricao: 'Tranças e cestos de fibras vegetais' },
  { codigo: '46021910', descricao: 'Esteiras de fibras vegetais' },
  { codigo: '47032100', descricao: 'Pasta de celulose de coníferas' },
  { codigo: '47071000', descricao: 'Papel reciclado' },
  { codigo: '48010010', descricao: 'Papel jornal' },
  { codigo: '48021000', descricao: 'Papel kraft' },
  { codigo: '48025710', descricao: 'Papel offset' },
  { codigo: '48026110', descricao: 'Papel em bobinas' },
  { codigo: '48026210', descricao: 'Papel em folhas' },
  { codigo: '48030010', descricao: 'Papel higiênico' },
  { codigo: '48041110', descricao: 'Papel kraftliner' },
  { codigo: '48042900', descricao: 'Papel revestido' },
  { codigo: '48043110', descricao: 'Papel para sacos' },
  { codigo: '48051100', descricao: 'Papel ondulado' },
  { codigo: '48051900', descricao: 'Papel canelado' },
  { codigo: '48061000', descricao: 'Papel vegetal' },
  { codigo: '48070010', descricao: 'Papel cartão' },
  { codigo: '48101310', descricao: 'Papel couchê' },
  { codigo: '48101910', descricao: 'Papel para impressão' },
  { codigo: '48103110', descricao: 'Papel para embalagem' },
  { codigo: '48111010', descricao: 'Papel betumado' },
  { codigo: '48114110', descricao: 'Papel autoadesivo' },
  { codigo: '48115110', descricao: 'Papel plastificado' },
  { codigo: '48115910', descricao: 'Outros papéis revestidos' },
  { codigo: '48119010', descricao: 'Outros papéis' },
  { codigo: '48120000', descricao: 'Papel filtro' },
  { codigo: '48131000', descricao: 'Papel para cigarros' },
  { codigo: '48142000', descricao: 'Papel de parede' },
  { codigo: '48162010', descricao: 'Papel carbono' },
  { codigo: '48169010', descricao: 'Papel hectográfico' },
  { codigo: '48172000', descricao: 'Envelopes de papel' },
  { codigo: '48173000', descricao: 'Caixas de papel' },
  { codigo: '48181000', descricao: 'Papel higiênico em rolos' },
  { codigo: '48182000', descricao: 'Lenços de papel' },
  { codigo: '48183000', descricao: 'Toalhas de papel' },
  { codigo: '48184010', descricao: 'Absorventes de papel' },
  { codigo: '48185000', descricao: 'Vestuário de papel' },
  { codigo: '48189010', descricao: 'Outros artigos de papel' },
  { codigo: '48191000', descricao: 'Caixas de papelão' },
  { codigo: '48192000', descricao: 'Caixas de papelão ondulado' },
  { codigo: '48193000', descricao: 'Sacos de papel' },
  { codigo: '48194000', descricao: 'Embalagens de papel' },
  { codigo: '48195000', descricao: 'Outras embalagens de papel' },
  { codigo: '48201000', descricao: 'Livros de registro' },
  { codigo: '48202000', descricao: 'Cadernos' },
  { codigo: '48203000', descricao: 'Pastas de papel' },
  { codigo: '48204000', descricao: 'Formulários de papel' },
  { codigo: '48205000', descricao: 'Álbuns de papel' },
  { codigo: '48209000', descricao: 'Outros artigos de papelaria' },
  { codigo: '48211000', descricao: 'Etiquetas de papel' },
  { codigo: '48219000', descricao: 'Outras etiquetas de papel' },
  { codigo: '48221000', descricao: 'Bobinas de papel' },
  { codigo: '48229000', descricao: 'Outros artigos de pasta de celulose' },
  { codigo: '48232010', descricao: 'Filtros de papel' },
  { codigo: '48234000', descricao: 'Papel diazo' },
  { codigo: '48236100', descricao: 'Copos de papel' },
  { codigo: '48236910', descricao: 'Outros copos de papel' },
  { codigo: '48237010', descricao: 'Bandejas de papel' },
];

async function main() {
  console.log('🌱 Iniciando seed do Base Brasil...');

  for (const [uf, cidades] of Object.entries(cidadesPorUf)) {
    for (const cidade of cidades) {
      await prisma.cidadeIbge.upsert({
        where: { codigo: cidade.codigo },
        update: { nome: cidade.nome, uf, regiao: cidade.regiao },
        create: {
          codigo: cidade.codigo,
          nome: cidade.nome,
          uf,
          regiao: cidade.regiao,
        },
      });
    }
    console.log(`  ✅ ${uf}: ${cidades.length} cidades`);
  }

  for (const cfop of cfops) {
    await prisma.cfop.upsert({
      where: { codigo: cfop.codigo },
      update: { descricao: cfop.descricao, tipo: cfop.tipo },
      create: cfop,
    });
  }
  console.log(`  ✅ CFOPs: ${cfops.length} códigos (${cfops.filter(c => c.tipo === 'ENTRADA').length} entrada, ${cfops.filter(c => c.tipo === 'SAIDA').length} saída)`);

  for (const ncm of ncms) {
    await prisma.ncm.upsert({
      where: { codigo: ncm.codigo },
      update: { descricao: ncm.descricao },
      create: ncm,
    });
  }
  console.log(`  ✅ NCMs: ${ncms.length} códigos`);

  console.log('✅ Seed concluído com sucesso!');
}

main()
  .catch((e) => {
    console.error('❌ Erro no seed:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
